"""Execute real C plans on assembled, relocated PIO words with live neighbors."""
import ctypes as C
import os
from pathlib import Path
import random
import re
import shutil
import subprocess

import pytest
from tdma_flight_pio_model import Machine, bytes_to_bits, LIVE

ROOT = Path(__file__).resolve().parents[2]


class Run(C.Structure):
    _fields_ = [(name, C.c_uint32) for name in
                ("control", "write_address", "transfer_count", "read_address")]


class Plan(C.Structure):
    _fields_ = [("run", Run * 6), ("token", C.c_uint32 * 259)] + [
        (name, C.c_uint32) for name in ("run_count", "token_word_count",
                                      "command_word_count", "replacement_byte_count")]


class Config(C.Structure):
    _fields_ = [(name, C.c_uint32) for name in
                ("physical_byte_count", "outer_header_size", "alignment_byte_shift",
                 "alignment_bit_shift", "local_slot_id", "header_write_mask", "final_bit_pc")]


@pytest.fixture(scope="module")
def engine(tmp_path_factory):
    directory = tmp_path_factory.mktemp("bit-pipeline")
    gcc = os.environ.get("HOST_CC") or shutil.which("gcc") or "D:/Microsoft/mingw64/bin/gcc.exe"
    pioasm = os.environ.get("PIOASM") or shutil.which("pioasm") or str(
        Path.home() / ".pico-sdk/tools/2.2.0/pioasm/pioasm.exe")
    libpath = directory / ("overlay.dll" if os.name == "nt" else "overlay.so")
    subprocess.run([gcc, "-std=c11", "-O2", "-Wall", "-Wextra", "-Werror", "-shared",
                    "-I" + str(ROOT / "components/tdma/inc"),
                    str(ROOT / "components/tdma/src/tdma_flight_overlay.c"),
                    str(ROOT / "components/tdma/src/tdma_transport_frame.c"),
                    "-o", str(libpath)], check=True, capture_output=True)
    header = directory / "tdma.pio.h"
    subprocess.run([pioasm, "-o", "c-sdk", str(ROOT / "components/tdma/src/tdma_pio_spi.pio"),
                    str(header)], check=True, capture_output=True)
    source = header.read_text(encoding="utf-8")
    program = "tdma_pio_spi_flight_process_follower"
    body = source.split(f"{program}_program_instructions[] = {{", 1)[1].split("};", 1)[0]
    instructions = [int(value, 16) for value in re.findall(r"0x([0-9a-f]{4}),", body)]
    final = int(re.search(rf"#define {program}_offset_final_bit (\d+)u", source)[1])
    wrap = int(re.search(rf"#define {program}_wrap (\d+)", source)[1])
    assert len(instructions) == 28 and instructions[final] == LIVE
    lib = C.CDLL(str(libpath))
    lib.tdma_flight_overlay_build_plan.argtypes = [C.c_void_p, C.c_void_p, C.c_size_t,
        C.c_void_p, C.c_size_t, C.POINTER(Config), C.POINTER(Plan)]
    lib.tdma_flight_overlay_build_plan.restype = C.c_bool
    lib.tdma_transport_frame_resident_overlay_header_mask.restype = C.c_uint32
    return lib, instructions, final, wrap


def pack(bits):
    return bytes(sum(bits[i + k] << (7 - k) for k in range(8))
                 for i in range(0, len(bits), 8))


def case(engine, slot, shift, byte_shift, installed, delay, period, high, rx_drop):
    lib, instructions, final, wrap = engine
    # Exactly the relocation performed by the SDK PIO loader; OUT EXEC tokens
    # are generated by C with the installed final PC, not relocated afterwards.
    program = [0] * installed + [
        (word & ~31) | ((word & 31) + installed) if word >> 13 == 0 else word
        for word in instructions]
    rising = [i for i, word in enumerate(program) if word == 0x2081]
    assert len(rising) == 3
    for i, position in enumerate(rising):
        program[position] |= (delay - 2 if i == 0 else delay) << 8
    rng = random.Random(slot * 8192 + shift * 256 + byte_shift)
    old = bytes(rng.randrange(256) for _ in range(292))
    updated = bytearray(old)
    start, end = 32 + slot * 32, 64 + slot * 32
    updated[start:end] = bytes(rng.randrange(256) for _ in range(32))
    updated[start] = old[start]  # Equal-to-snapshot forced update still owns this byte.
    header_mask = lib.tdma_transport_frame_resident_overlay_header_mask()
    for i in range(32):
        if header_mask & (1 << i): updated[i] ^= 255
    forced = (C.c_uint32 * 9)()
    forced[slot] = 0xFFFFFFFF
    config = Config(307, 4, byte_shift, shift, slot, header_mask, final + installed)
    plan = Plan()
    assert lib.tdma_flight_overlay_build_plan(old, bytes(updated), len(old), forced,
                                             len(forced), C.byref(config), C.byref(plan))
    words = []
    for run in plan.run[:plan.run_count]:
        words.extend(plan.token[run.read_address:run.read_address + run.transfer_count]
                     if run.control else [LIVE << 16 | LIVE] * run.transfer_count)
    tokens = [half for word in words for half in (word >> 16, word & 65535)]
    physical, expected = [], []
    base = (4 + byte_shift) * 8 + shift
    for frame in range(2):
        live = bytearray(rng.randrange(256) for _ in range(292))
        wire = [rng.randrange(2) for _ in range(307 * 8)]
        wire[base:base + len(live) * 8] = bytes_to_bits(live)
        physical.append(pack(wire))
        live[start:end] = updated[start:end]
        for i in range(32):
            if header_mask & (1 << i): live[i] = updated[i]
        oracle = wire[:]
        oracle[base:base + len(live) * 8] = bytes_to_bits(live)
        previous = [0] * 8 if not frame else bytes_to_bits(physical[frame - 1][-1:])
        expected.extend(previous + oracle[:-8])
    machine = Machine(physical, [tokens, tokens], program=program, entry=installed,
                      wrap=wrap + installed, final=final + installed, period=period,
                      high=high, rx_drop=rx_drop).run()
    assert [bit for _, bit in machine.output] == expected
    assert machine.pushes == ([] if rx_drop else list(physical[0] + physical[1]))
    for index, (frame, ordinal, sample, _) in enumerate(machine.samples):
        assert index == frame * machine.frame_bits + ordinal
        assert sample == machine.starts[frame] + ordinal * period + delay + 1
    return machine


@pytest.mark.parametrize("installed,rx_drop", [(0, False), (4, True)])
@pytest.mark.parametrize("byte_shift", [0, 9])
@pytest.mark.parametrize("shift", range(8))
def test_live_neighbor_and_rx_loss(engine, installed, rx_drop, byte_shift, shift):
    for slot in range(8):
        case(engine, slot, shift, byte_shift, installed, 15, 25, 12, rx_drop)


@pytest.mark.parametrize("delay,high", [(2, 4), (2, 8), (15, 12), (31, 16)])
def test_complete_byte_budget_and_negative_control(engine, delay, high):
    bound = max(delay + 2, high) + 7
    case(engine, 3, 5, 0, 4, delay, bound, high, False)
    with pytest.raises(AssertionError):
        case(engine, 3, 5, 0, 4, delay, bound - 1, high, False)
