#ifndef BOOTLOADER_CONFIG_H
#define BOOTLOADER_CONFIG_H

#include <stdint.h>

#define BOOTLOADER_APP_VECTOR_OFFSET OTA_SLOT_A_OFFSET
#define BOOTLOADER_STAGING_SLOT      OTA_SLOT_B
#define BOOTLOADER_ACTIVE_SLOT       OTA_SLOT_A

#define BOOTLOADER_FLASH_COPY_BUFFER_SIZE DRV_FLASH_PAGE_SIZE
#define BOOTLOADER_MAX_BOOT_ATTEMPTS      3u

#endif
