#ifndef SCPI_USER_CONFIG_H
#define SCPI_USER_CONFIG_H

#define USE_FULL_ERROR_LIST 0
#define USE_USER_ERROR_LIST 0
#define USE_DEVICE_DEPENDENT_ERROR_INFORMATION 0
#define USE_MEMORY_ALLOCATION_FREE 0
#define USE_COMMAND_TAGS 0
#define USE_DEPRECATED_FUNCTIONS 0
#define USE_UNITS_IMPERIAL 0
#define USE_UNITS_ANGLE 0
#define USE_UNITS_PARTICLES 0
#define USE_UNITS_DISTANCE 0
#define USE_UNITS_MAGNETIC 0
#define USE_UNITS_LIGHT 0
#define USE_UNITS_ENERGY_FORCE_MASS 0
#define USE_UNITS_TIME 1
#define USE_UNITS_TEMPERATURE 0
#define USE_UNITS_RATIO 0
#define USE_UNITS_POWER 0
#define USE_UNITS_FREQUENCY 1
#define USE_UNITS_ELECTRIC 0
#define USE_UNITS_ELECTRIC_CHARGE_CONDUCTANCE 0

#endif
