#ifndef OTA_ERROR_H
#define OTA_ERROR_H

typedef enum {
    OTA_ERR_NONE = 0,
    OTA_ERR_BUSY,
    OTA_ERR_INVALID_STATE,
    OTA_ERR_IMAGE_TOO_LARGE,
    OTA_ERR_BAD_HEADER,
    OTA_ERR_BOARD_MISMATCH,
    OTA_ERR_VERSION_REJECTED,
    OTA_ERR_FLASH_ERASE,
    OTA_ERR_FLASH_PROGRAM,
    OTA_ERR_READBACK,
    OTA_ERR_CRC,
    OTA_ERR_VECTOR,
    OTA_ERR_METADATA,
    OTA_ERR_ABORTED,
    OTA_ERR_BOOT_ROLLBACK,
    OTA_ERR_QUEUE_FULL,
    OTA_ERR_BAD_ARGUMENT,
    OTA_ERR_SIGNATURE_INVALID,
    OTA_ERR_SECURITY_COUNTER_ROLLBACK,
} ota_error_t;

#endif
