#ifndef APP_REALTIME_SCHEDULE_H
#define APP_REALTIME_SCHEDULE_H

#include <stdint.h>

#include "project_config.h"

/* Keep this table ordered. app_runtime.c performs compile-time adjacency,
 * containment, WCET, board-clock, and minimum-wire-time checks. */
#define APP_REALTIME_PHASE_TABLE(X) \
    X(TDMA, \
      PROJECT_CORE1_PHASE_TDMA_START_CYCLE, \
      PROJECT_CORE1_PHASE_TDMA_END_CYCLE, \
      PROJECT_CORE1_PHASE_TDMA_WCET_CYCLES) \
    X(VDC, \
      PROJECT_CORE1_PHASE_VDC_START_CYCLE, \
      PROJECT_CORE1_PHASE_VDC_END_CYCLE, \
      PROJECT_CORE1_PHASE_VDC_WCET_CYCLES) \
    X(DPLL, \
      PROJECT_CORE1_PHASE_DPLL_START_CYCLE, \
      PROJECT_CORE1_PHASE_DPLL_END_CYCLE, \
      PROJECT_CORE1_PHASE_DPLL_WCET_CYCLES) \
    X(CALIBRATION, \
      PROJECT_CORE1_PHASE_CALIBRATION_START_CYCLE, \
      PROJECT_CORE1_PHASE_CALIBRATION_END_CYCLE, \
      PROJECT_CORE1_PHASE_CALIBRATION_WCET_CYCLES) \
    X(SYNC_CAPTURE, \
      PROJECT_CORE1_PHASE_SYNC_CAPTURE_START_CYCLE, \
      PROJECT_CORE1_PHASE_SYNC_CAPTURE_END_CYCLE, \
      PROJECT_CORE1_PHASE_SYNC_CAPTURE_WCET_CYCLES) \
    X(REFMEM, \
      PROJECT_CORE1_PHASE_REFMEM_START_CYCLE, \
      PROJECT_CORE1_PHASE_REFMEM_END_CYCLE, \
      PROJECT_CORE1_PHASE_REFMEM_WCET_CYCLES) \
    X(MODEL, \
      PROJECT_CORE1_PHASE_MODEL_START_CYCLE, \
      PROJECT_CORE1_PHASE_MODEL_END_CYCLE, \
      PROJECT_CORE1_PHASE_MODEL_WCET_CYCLES) \
    X(SYNC_TRIGGER, \
      PROJECT_CORE1_PHASE_SYNC_TRIGGER_START_CYCLE, \
      PROJECT_CORE1_PHASE_SYNC_TRIGGER_END_CYCLE, \
      PROJECT_CORE1_PHASE_SYNC_TRIGGER_WCET_CYCLES) \
    X(TRIGGER_MEASURE, \
      PROJECT_CORE1_PHASE_TRIGGER_MEASURE_START_CYCLE, \
      PROJECT_CORE1_PHASE_TRIGGER_MEASURE_END_CYCLE, \
      PROJECT_CORE1_PHASE_TRIGGER_MEASURE_WCET_CYCLES) \
    X(GUARD, \
      PROJECT_CORE1_PHASE_GUARD_START_CYCLE, \
      PROJECT_CORE1_PHASE_GUARD_END_CYCLE, \
      PROJECT_CORE1_PHASE_GUARD_WCET_CYCLES)

typedef enum {
#define APP_REALTIME_PHASE_ENUM(name, start, end, wcet) \
    APP_REALTIME_PHASE_##name,
    APP_REALTIME_PHASE_TABLE(APP_REALTIME_PHASE_ENUM)
#undef APP_REALTIME_PHASE_ENUM
    APP_REALTIME_PHASE_COUNT
} app_realtime_phase_id_t;

typedef struct {
    uint32_t start_cycle;
    uint32_t end_cycle;
    uint32_t wcet_cycles;
} app_realtime_phase_contract_t;

#endif
