#!/usr/bin/env python3
"""Send a unified OTA package to DHRT100 over USBTMC/VISA."""

from __future__ import annotations

import argparse
import binascii
import sys
import time
from pathlib import Path


DEFAULT_BLOCK_SIZE = 512
DEFAULT_TIMEOUT_MS = 5000
PACKAGE_MAGIC = 0x474B5054


def crc32(data: bytes) -> int:
    return binascii.crc32(data) & 0xFFFFFFFF


def scpi_block(data: bytes) -> bytes:
    length = str(len(data)).encode("ascii")
    return b"#" + str(len(length)).encode("ascii") + length + data


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("resource", help="VISA resource, for example USB0::0xCAFE::0x4030::SERIAL::INSTR")
    parser.add_argument("package", type=Path, help="unified OTA package generated by ota_packager")
    parser.add_argument("--block-size", type=int, default=DEFAULT_BLOCK_SIZE)
    parser.add_argument("--timeout-ms", type=int, default=DEFAULT_TIMEOUT_MS)
    parser.add_argument("--begin-timeout", type=float, default=60.0)
    parser.add_argument("--inter-block-delay", type=float, default=0.005)
    parser.add_argument("--progress-every", type=int, default=16)
    parser.add_argument("--boot", action="store_true", help="send SYST:OTA:BOOT after READY_TO_REBOOT")
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def validate_args(args: argparse.Namespace, package: bytes) -> None:
    if args.block_size <= 0 or args.block_size > 512:
        raise ValueError("block size must be in range 1..512")
    if args.block_size % 256 != 0:
        raise ValueError("block size must be 256 or 512 for current firmware")
    if args.inter_block_delay < 0.0:
        raise ValueError("inter-block delay must not be negative")
    if args.progress_every <= 0:
        raise ValueError("progress interval must be positive")
    if len(package) < 4 or int.from_bytes(package[0:4], "little") != PACKAGE_MAGIC:
        raise ValueError("input is not a unified OTA package")


def open_resource(resource: str, timeout_ms: int):
    try:
        import pyvisa
    except ImportError as exc:
        raise SystemExit("pyvisa is required: python -m pip install pyvisa") from exc

    rm = pyvisa.ResourceManager()
    inst = rm.open_resource(resource)
    inst.timeout = timeout_ms
    inst.write_termination = "\n"
    inst.read_termination = "\n"
    return rm, inst


def write_line(inst, command: str) -> None:
    inst.write_raw(command.encode("ascii") + b"\n")


def query(inst, command: str) -> str:
    return inst.query(command).strip()


def wait_for_state(inst, wanted: str, timeout_s: float) -> str:
    deadline = time.monotonic() + timeout_s
    last = ""
    while time.monotonic() < deadline:
        last = query(inst, "SYST:OTA:STAT?")
        print(f"status={last}")
        if wanted in last or "FAILED" in last or "ABORTED" in last:
            return last
        time.sleep(0.1)
    raise TimeoutError(f"timed out waiting for {wanted}, last response: {last}")


def wait_for_received_size(inst, expected_size: int, timeout_s: float) -> str:
    deadline = time.monotonic() + timeout_s
    last = ""
    while time.monotonic() < deadline:
        last = query(inst, "SYST:OTA:PROG?")
        print(f"progress={last}")
        try:
            received = int(last.split(",", 1)[0].strip(), 0)
        except (ValueError, IndexError):
            received = -1
        if received >= expected_size:
            return last
        if "FAILED" in last or "ABORTED" in last:
            return last
        time.sleep(0.1)
    raise TimeoutError(f"timed out waiting for received_size={expected_size}, last response: {last}")


def wait_for_state_leave(inst, state_name: str, timeout_s: float) -> str:
    deadline = time.monotonic() + timeout_s
    last = ""
    while time.monotonic() < deadline:
        last = query(inst, "SYST:OTA:STAT?")
        print(f"status={last}")
        if state_name not in last:
            return last
        if "FAILED" in last or "ABORTED" in last:
            return last
        time.sleep(0.1)
    raise TimeoutError(f"timed out waiting for state to leave {state_name}, last response: {last}")


def send_package(args: argparse.Namespace, package: bytes) -> str:
    package_crc = crc32(package)
    print(f"resource={args.resource}")
    print(f"package={args.package}")
    print(f"size={len(package)}")
    print(f"crc32=0x{package_crc:08X}")
    print(f"block_size={args.block_size}")
    print(f"begin=SYST:OTA:PBEGIN {len(package)},{package_crc}")
    if args.dry_run:
        return ""

    rm, inst = open_resource(args.resource, args.timeout_ms)
    try:
        print(f"idn={query(inst, '*IDN?')}")
        write_line(inst, f"SYST:OTA:PBEGIN {len(package)},{package_crc}")
        status = wait_for_state(inst, "RECEIVING", args.begin_timeout)
        if "FAILED" in status or "ABORTED" in status:
            return status

        for offset in range(0, len(package), args.block_size):
            chunk = package[offset : offset + args.block_size]
            inst.write_raw(b"SYST:OTA:DATA " + scpi_block(chunk) + b"\n")
            block_index = offset // args.block_size
            if args.inter_block_delay > 0.0:
                time.sleep(args.inter_block_delay)

            if block_index == 0:
                first_block_status = query(inst, "SYST:OTA:STAT?")
                print(f"status={first_block_status}")
                if "FAILED" in first_block_status or "ABORTED" in first_block_status:
                    return first_block_status
                if "RECEIVING" in first_block_status:
                    left_status = wait_for_state_leave(inst, "RECEIVING", args.begin_timeout)
                    if "FAILED" in left_status or "ABORTED" in left_status:
                        return left_status
                resumed_status = wait_for_state(inst, "RECEIVING", args.begin_timeout)
                if "FAILED" in resumed_status or "ABORTED" in resumed_status:
                    return resumed_status

            if block_index == 0 or block_index % args.progress_every == 0:
                progress = query(inst, "SYST:OTA:PROG?")
                print(f"progress={progress}")

        progress = wait_for_received_size(inst, len(package), args.begin_timeout)
        if "FAILED" in progress or "ABORTED" in progress:
            return progress

        write_line(inst, "SYST:OTA:END")
        final_status = wait_for_state(inst, "READY_TO_REBOOT", args.begin_timeout)
        if args.boot and "READY_TO_REBOOT" in final_status:
            write_line(inst, "SYST:OTA:BOOT")
            print("boot=requested")
        return final_status
    finally:
        try:
            inst.close()
        finally:
            rm.close()


def main() -> int:
    args = parse_args()
    package = args.package.read_bytes()
    validate_args(args, package)
    final_status = send_package(args, package)
    if args.dry_run:
        return 0
    if "READY_TO_REBOOT" not in final_status:
        print(f"unexpected_final_status={final_status}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
