#ifndef PROJECT_CONFIG_H
#define PROJECT_CONFIG_H

#include <stdint.h>

#if __has_include("project_build_info.h")
#include "project_build_info.h"
#else
static const char g_project_build_id[] = "dev";
#endif

#define PROJECT_NAME "DHRT100"
#define PROJECT_PRODUCT_ID "DHRT100"
#define PROJECT_HARDWARE_ID "dhrt100"
#define PROJECT_VENDOR_NAME "GTS"
#define PROJECT_MODEL_NAME "DHRT100"
#define PROJECT_MODEL_SHORT_NAME PROJECT_MODEL_NAME
#define PROJECT_MODEL_DESCRIPTION "Distributed Trigger Controller"
#define PROJECT_VERSION_MAJOR 0u
#define PROJECT_VERSION_MINOR 1u
#define PROJECT_VERSION_PATCH 0u
#define PROJECT_VERSION_STRING "0.1.0"

#define PROJECT_BOOTLOADER_VERSION_MAJOR 0u
#define PROJECT_BOOTLOADER_VERSION_MINOR 1u
#define PROJECT_BOOTLOADER_VERSION_PATCH 0u
#define PROJECT_BOOTLOADER_MIN_VERSION_MAJOR 0u
#define PROJECT_BOOTLOADER_MIN_VERSION_MINOR 1u
#define PROJECT_BOOTLOADER_MIN_VERSION_PATCH 0u

#define PROJECT_LOOP_PERIOD_MS 100u
#define PROJECT_HEALTH_LOG_PERIOD_MS 1000u
#define PROJECT_WATCHDOG_TIMEOUT_MS 3000u

/* Core1 deterministic schedule. A clk_sys cycle is the only source-of-truth
 * unit: ns/us values are derived presentation and must never drive admission.
 * Each phase owns [START, END) and its WCET; unused cycles are not borrowed by
 * another phase. The tail guard is deliberately not executable load budget. */
#define PROJECT_CORE1_CYCLE_RATE_HZ 1000u
#define PROJECT_CORE1_CYCLE_CYCLES 250000u
#define PROJECT_CORE1_SCHEDULE_WARMUP_CYCLES 8u
#define PROJECT_CORE1_TDMA_SOFTWARE_MARGIN_CYCLES 30000u

#define PROJECT_CORE1_PHASE_TDMA_START_CYCLE 0u
#define PROJECT_CORE1_PHASE_TDMA_END_CYCLE 100000u
#define PROJECT_CORE1_PHASE_TDMA_WCET_CYCLES 95000u

#define PROJECT_CORE1_PHASE_VDC_START_CYCLE 100000u
#define PROJECT_CORE1_PHASE_VDC_END_CYCLE 145000u
#define PROJECT_CORE1_PHASE_VDC_WCET_CYCLES 44000u

#define PROJECT_CORE1_PHASE_DPLL_START_CYCLE 145000u
#define PROJECT_CORE1_PHASE_DPLL_END_CYCLE 177000u
#define PROJECT_CORE1_PHASE_DPLL_WCET_CYCLES 31000u

#define PROJECT_CORE1_PHASE_CALIBRATION_START_CYCLE 177000u
#define PROJECT_CORE1_PHASE_CALIBRATION_END_CYCLE 212000u
#define PROJECT_CORE1_PHASE_CALIBRATION_WCET_CYCLES 34000u

#define PROJECT_CORE1_PHASE_SYNC_CAPTURE_START_CYCLE 212000u
#define PROJECT_CORE1_PHASE_SYNC_CAPTURE_END_CYCLE 217000u
#define PROJECT_CORE1_PHASE_SYNC_CAPTURE_WCET_CYCLES 4000u

#define PROJECT_CORE1_PHASE_REFMEM_START_CYCLE 217000u
#define PROJECT_CORE1_PHASE_REFMEM_END_CYCLE 221000u
#define PROJECT_CORE1_PHASE_REFMEM_WCET_CYCLES 3000u

/* The VDC/DPLL RefMem mirror is a fixed part of the realtime contract.  Its
 * cost is expressed in clk_sys cycles so a larger payload cannot silently
 * consume the following MODEL/trigger phases.  The byte costs are a
 * conservative upper-bound for the volatile copy and payload CRC loops; the
 * fixed term covers seqlock/field assembly and publication.  Keep the
 * resulting WCET below the phase WCET and change both values together when
 * the vector schema changes. */
#define PROJECT_CORE1_REFMEM_VECTOR_MIRROR_MAX_PAYLOAD_BYTES 448u
#define PROJECT_CORE1_REFMEM_VECTOR_MIRROR_COPY_CYCLES_PER_BYTE 2u
#define PROJECT_CORE1_REFMEM_VECTOR_MIRROR_CRC_CYCLES_PER_BYTE 2u
#define PROJECT_CORE1_REFMEM_VECTOR_MIRROR_FIXED_CYCLES 256u
#define PROJECT_CORE1_REFMEM_VECTOR_MIRROR_WCET_CYCLES \
    (PROJECT_CORE1_REFMEM_VECTOR_MIRROR_FIXED_CYCLES + \
     PROJECT_CORE1_REFMEM_VECTOR_MIRROR_MAX_PAYLOAD_BYTES * \
         (PROJECT_CORE1_REFMEM_VECTOR_MIRROR_COPY_CYCLES_PER_BYTE + \
          PROJECT_CORE1_REFMEM_VECTOR_MIRROR_CRC_CYCLES_PER_BYTE))

#define PROJECT_CORE1_PHASE_MODEL_START_CYCLE 221000u
#define PROJECT_CORE1_PHASE_MODEL_END_CYCLE 224000u
#define PROJECT_CORE1_PHASE_MODEL_WCET_CYCLES 3000u

#define PROJECT_CORE1_PHASE_SYNC_TRIGGER_START_CYCLE 224000u
#define PROJECT_CORE1_PHASE_SYNC_TRIGGER_END_CYCLE 246000u
#define PROJECT_CORE1_PHASE_SYNC_TRIGGER_WCET_CYCLES 21000u

#define PROJECT_CORE1_PHASE_TRIGGER_MEASURE_START_CYCLE 246000u
#define PROJECT_CORE1_PHASE_TRIGGER_MEASURE_END_CYCLE 248000u
#define PROJECT_CORE1_PHASE_TRIGGER_MEASURE_WCET_CYCLES 2000u

#define PROJECT_CORE1_PHASE_GUARD_START_CYCLE 248000u
#define PROJECT_CORE1_PHASE_GUARD_END_CYCLE PROJECT_CORE1_CYCLE_CYCLES
#define PROJECT_CORE1_PHASE_GUARD_WCET_CYCLES 0u

#ifndef PROJECT_ENABLE_WATCHDOG_TEST
#define PROJECT_ENABLE_WATCHDOG_TEST 0
#endif

#ifndef PROJECT_ENABLE_HEALTH_LOG
#define PROJECT_ENABLE_HEALTH_LOG 0
#endif

#ifndef PROJECT_ENABLE_TDMA_RING_LOG
#define PROJECT_ENABLE_TDMA_RING_LOG 0
#endif

#ifndef PROJECT_ENABLE_LOG_UART_OUTPUT
#define PROJECT_ENABLE_LOG_UART_OUTPUT 1
#endif

#ifndef PROJECT_ENABLE_OTA_FAULT_INJECTION
#define PROJECT_ENABLE_OTA_FAULT_INJECTION 0
#endif

#ifndef PROJECT_ENABLE_FLASH_VALIDATION
#define PROJECT_ENABLE_FLASH_VALIDATION 0
#endif

#ifndef PROJECT_OTA_DEFAULT_BOOT_MODE_DIRECT_AB
#define PROJECT_OTA_DEFAULT_BOOT_MODE_DIRECT_AB 1
#endif

#define BOARD_SPI_BAUD_HZ 10000000u
#define BOARD_UART_BAUD_HZ 115200u

#ifndef PROJECT_ENABLE_USB_STDIO
#define PROJECT_ENABLE_USB_STDIO 1
#endif

#ifndef PROJECT_ENABLE_UART_STDIO
#define PROJECT_ENABLE_UART_STDIO 0
#endif

#ifndef PROJECT_ENABLE_USBTMC
#define PROJECT_ENABLE_USBTMC 0
#endif

#ifndef PROJECT_ENABLE_USB_RUNTIME_SWITCH
#define PROJECT_ENABLE_USB_RUNTIME_SWITCH 0
#endif

#ifndef PROJECT_USB_DEFAULT_MODE_USBTMC
#define PROJECT_USB_DEFAULT_MODE_USBTMC 0
#endif

#ifndef PROJECT_USB_VID
#define PROJECT_USB_VID 0xCAFEu
#endif

#ifndef PROJECT_USB_PID_CDC
#define PROJECT_USB_PID_CDC 0x402Fu
#endif

#ifndef PROJECT_USB_PID_USBTMC
#define PROJECT_USB_PID_USBTMC 0x4030u
#endif

#define PROJECT_USB_MANUFACTURER PROJECT_VENDOR_NAME
#define PROJECT_USB_PRODUCT "GTS DHRT100"
#define PROJECT_USB_PRODUCT_USBTMC PROJECT_USB_PRODUCT
#define PROJECT_USB_PRODUCT_CDC PROJECT_USB_PRODUCT

#endif
