#ifndef PROJECT_CONFIG_H
#define PROJECT_CONFIG_H

#include <stdint.h>

#define PROJECT_NAME "RP2350_TRIG"
#define PROJECT_VERSION_MAJOR 0u
#define PROJECT_VERSION_MINOR 1u
#define PROJECT_VERSION_PATCH 0u

#define PROJECT_LOOP_PERIOD_MS 100u
#define PROJECT_HEALTH_LOG_PERIOD_MS 1000u
#define PROJECT_WATCHDOG_TIMEOUT_MS 3000u

#define BOARD_SPI_BAUD_HZ 10000000u
#define BOARD_UART_BAUD_HZ 115200u

#ifndef PROJECT_ENABLE_USB_STDIO
#define PROJECT_ENABLE_USB_STDIO 1
#endif

#ifndef PROJECT_ENABLE_UART_STDIO
#define PROJECT_ENABLE_UART_STDIO 0
#endif

#endif
