#ifndef PROJECT_CONFIG_H
#define PROJECT_CONFIG_H

#include <stdint.h>

#if __has_include("project_build_info.h")
#include "project_build_info.h"
#else
static const char g_project_build_id[] = "dev";
#endif

#define PROJECT_NAME "DHRT100"
#define PROJECT_PRODUCT_ID "DHRT100"
#define PROJECT_HARDWARE_ID "dhrt100"
#define PROJECT_VENDOR_NAME "GTS"
#define PROJECT_MODEL_NAME "DHRT100"
#define PROJECT_MODEL_SHORT_NAME PROJECT_MODEL_NAME
#define PROJECT_MODEL_DESCRIPTION "Distributed Trigger Controller"
#define PROJECT_VERSION_MAJOR 0u
#define PROJECT_VERSION_MINOR 1u
#define PROJECT_VERSION_PATCH 0u
#define PROJECT_VERSION_STRING "0.1.0"

#define PROJECT_BOOTLOADER_VERSION_MAJOR 0u
#define PROJECT_BOOTLOADER_VERSION_MINOR 1u
#define PROJECT_BOOTLOADER_VERSION_PATCH 0u
#define PROJECT_BOOTLOADER_MIN_VERSION_MAJOR 0u
#define PROJECT_BOOTLOADER_MIN_VERSION_MINOR 1u
#define PROJECT_BOOTLOADER_MIN_VERSION_PATCH 0u

#define PROJECT_LOOP_PERIOD_MS 100u
#define PROJECT_HEALTH_LOG_PERIOD_MS 1000u
#define PROJECT_WATCHDOG_TIMEOUT_MS 3000u

/* Core1 deterministic schedule. A clk_sys cycle is the only source-of-truth
 * unit: ns/us values are derived presentation and must never drive admission.
 * Each phase owns [START, END) and its WCET; unused cycles are not borrowed by
 * another phase. The tail guard is deliberately not executable load budget. */
/* Periods are exact clk_sys counts, including non-integer-Hz cadences.
 * Runtime profile selection is allowed only through the stopped owner gate. */
#define PROJECT_CORE1_PROFILE_1500US_CYCLES 375000u
#define PROJECT_CORE1_PROFILE_5MS_CYCLES 1250000u
#define PROJECT_CORE1_PROFILE_10MS_CYCLES 2500000u
#define PROJECT_CORE1_PROFILE_15MS_CYCLES 3750000u
#define PROJECT_CORE1_CYCLE_CYCLES PROJECT_CORE1_PROFILE_1500US_CYCLES
#define PROJECT_CORE1_SCHEDULE_WARMUP_CYCLES 8u
#define PROJECT_CORE1_TDMA_SOFTWARE_MARGIN_CYCLES 30000u

/* First ingress candidate, not a measured IRQ WCET. The physical owner rejects
 * faster wire profiles for this lane without disabling ordinary TDMA. All
 * seven interruptible phases reserve a pending event plus one new arrival.
 * Longer TDMA windows derive a larger quota in app_realtime_profile.c. */
#define PROJECT_CORE1_PRIORITY_RX_IRQ_CYCLES 2500u
#define PROJECT_CORE1_PRIORITY_RX_TAIL_CYCLES 500u
#define PROJECT_CORE1_PRIORITY_RX_MIN_PHYSICAL_CYCLES 250000u
#define PROJECT_CORE1_PRIORITY_RX_CLOSE_MARGIN_CYCLES 1000u
#define PROJECT_CORE1_PRIORITY_RX_CLOSE_CYCLES \
    (PROJECT_CORE1_PRIORITY_RX_IRQ_CYCLES + \
     PROJECT_CORE1_PRIORITY_RX_CLOSE_MARGIN_CYCLES)
#define PROJECT_CORE1_PRIORITY_RX_BASE_QUOTA 2u
#define PROJECT_CORE1_PRIORITY_RX_PHASE_CYCLES \
    (PROJECT_CORE1_PRIORITY_RX_BASE_QUOTA * PROJECT_CORE1_PRIORITY_RX_IRQ_CYCLES)
#define PROJECT_CORE1_PRIORITY_RX_RESERVATION_CYCLES \
    (7u * (PROJECT_CORE1_PRIORITY_RX_PHASE_CYCLES + \
           PROJECT_CORE1_PRIORITY_RX_CLOSE_CYCLES))
#define PROJECT_CORE1_TDMA_BACKGROUND_WCET_CYCLES \
    (212500u - PROJECT_CORE1_PRIORITY_RX_RESERVATION_CYCLES)
/* Candidate for a cached RUN handoff when the full TDMA WCET cannot fit.
 * It uses only TDMA's existing foreground interval, never a new phase. */
#define PROJECT_CORE1_RUN_OUTPUT_HANDOFF_WCET_CYCLES 20000u

#define PROJECT_CORE1_PHASE_TDMA_START_CYCLE 0u
#define PROJECT_CORE1_PHASE_TDMA_WCET_CYCLES \
    (PROJECT_CORE1_TDMA_BACKGROUND_WCET_CYCLES + PROJECT_CORE1_PRIORITY_RX_PHASE_CYCLES)
#define PROJECT_CORE1_PHASE_TDMA_END_CYCLE \
    (PROJECT_CORE1_PHASE_TDMA_WCET_CYCLES + PROJECT_CORE1_PRIORITY_RX_CLOSE_CYCLES + 5000u)

#define PROJECT_CORE1_PHASE_VDC_START_CYCLE PROJECT_CORE1_PHASE_TDMA_END_CYCLE
#define PROJECT_CORE1_PHASE_VDC_WCET_CYCLES (42000u + PROJECT_CORE1_PRIORITY_RX_PHASE_CYCLES)
#define PROJECT_CORE1_PHASE_VDC_END_CYCLE \
    (PROJECT_CORE1_PHASE_VDC_START_CYCLE + PROJECT_CORE1_PHASE_VDC_WCET_CYCLES + \
     PROJECT_CORE1_PRIORITY_RX_CLOSE_CYCLES + 1000u)

#define PROJECT_CORE1_PHASE_DPLL_START_CYCLE PROJECT_CORE1_PHASE_VDC_END_CYCLE
/* The dispatcher reaches a phase boundary with finite polling/entry jitter.
 * Reserve this headroom in the static table even when DPLL is disabled. It
 * is not additional service WCET and cannot be borrowed from a later phase.
 * Later phases move together; the remaining tail guard is still idle. */
#define PROJECT_CORE1_DPLL_ENTRY_MARGIN_CYCLES 1000u
#define PROJECT_CORE1_PHASE_DPLL_END_CYCLE \
    (PROJECT_CORE1_PHASE_DPLL_START_CYCLE + \
     PROJECT_CORE1_PHASE_DPLL_WCET_CYCLES + PROJECT_CORE1_DPLL_ENTRY_MARGIN_CYCLES + \
     PROJECT_CORE1_PRIORITY_RX_CLOSE_CYCLES)
#define PROJECT_CORE1_PHASE_DPLL_WCET_CYCLES (34000u + PROJECT_CORE1_PRIORITY_RX_PHASE_CYCLES)

#define PROJECT_CORE1_PHASE_CALIBRATION_START_CYCLE PROJECT_CORE1_PHASE_DPLL_END_CYCLE
#define PROJECT_CORE1_PHASE_CALIBRATION_WCET_CYCLES (14000u + PROJECT_CORE1_PRIORITY_RX_PHASE_CYCLES)
#define PROJECT_CORE1_PHASE_CALIBRATION_END_CYCLE \
    (PROJECT_CORE1_PHASE_CALIBRATION_START_CYCLE + PROJECT_CORE1_PHASE_CALIBRATION_WCET_CYCLES + \
     PROJECT_CORE1_PRIORITY_RX_CLOSE_CYCLES + 1000u)

#define PROJECT_CORE1_PHASE_SYNC_CAPTURE_START_CYCLE PROJECT_CORE1_PHASE_CALIBRATION_END_CYCLE
#define PROJECT_CORE1_PHASE_SYNC_CAPTURE_WCET_CYCLES (4000u + PROJECT_CORE1_PRIORITY_RX_PHASE_CYCLES)
#define PROJECT_CORE1_PHASE_SYNC_CAPTURE_END_CYCLE \
    (PROJECT_CORE1_PHASE_SYNC_CAPTURE_START_CYCLE + PROJECT_CORE1_PHASE_SYNC_CAPTURE_WCET_CYCLES + \
     PROJECT_CORE1_PRIORITY_RX_CLOSE_CYCLES + 1000u)

#define PROJECT_CORE1_PHASE_REFMEM_START_CYCLE PROJECT_CORE1_PHASE_SYNC_CAPTURE_END_CYCLE
#define PROJECT_CORE1_PHASE_REFMEM_WCET_CYCLES (24000u + PROJECT_CORE1_PRIORITY_RX_PHASE_CYCLES)
#define PROJECT_CORE1_PHASE_REFMEM_END_CYCLE \
    (PROJECT_CORE1_PHASE_REFMEM_START_CYCLE + PROJECT_CORE1_PHASE_REFMEM_WCET_CYCLES + \
     PROJECT_CORE1_PRIORITY_RX_CLOSE_CYCLES + 1000u)

/* The VDC/DPLL RefMem mirror is a fixed part of the realtime contract.  Its
 * cost is expressed in clk_sys cycles so a larger payload cannot silently
 * consume the following MODEL/trigger phases.  The byte costs are a
 * conservative upper-bound for the volatile copy and payload CRC loops; the
 * fixed term covers seqlock/field assembly and publication.  Keep the
 * resulting WCET below the phase WCET and change both values together when
 * the vector schema changes. */
#define PROJECT_CORE1_REFMEM_VECTOR_MIRROR_MAX_PAYLOAD_BYTES 448u
#define PROJECT_CORE1_REFMEM_VECTOR_MIRROR_COPY_CYCLES_PER_BYTE 2u
#define PROJECT_CORE1_REFMEM_VECTOR_MIRROR_CRC_CYCLES_PER_BYTE 2u
#define PROJECT_CORE1_REFMEM_VECTOR_MIRROR_FIXED_CYCLES 256u
#define PROJECT_CORE1_REFMEM_VECTOR_MIRROR_WCET_CYCLES \
    (PROJECT_CORE1_REFMEM_VECTOR_MIRROR_FIXED_CYCLES + \
     PROJECT_CORE1_REFMEM_VECTOR_MIRROR_MAX_PAYLOAD_BYTES * \
         (PROJECT_CORE1_REFMEM_VECTOR_MIRROR_COPY_CYCLES_PER_BYTE + \
          PROJECT_CORE1_REFMEM_VECTOR_MIRROR_CRC_CYCLES_PER_BYTE))
#define PROJECT_CORE1_REFMEM_VECTOR_MIRROR_MEASURED_MAX_CYCLES 21675u
#define PROJECT_CORE1_REFMEM_VECTOR_MIRROR_MEASUREMENT_MARGIN_CYCLES 2000u
#define PROJECT_CORE1_REFMEM_VECTOR_MIRROR_REQUIRED_CYCLES \
    (PROJECT_CORE1_REFMEM_VECTOR_MIRROR_MEASURED_MAX_CYCLES + \
     PROJECT_CORE1_REFMEM_VECTOR_MIRROR_MEASUREMENT_MARGIN_CYCLES)

#define PROJECT_CORE1_PHASE_MODEL_START_CYCLE PROJECT_CORE1_PHASE_REFMEM_END_CYCLE
#define PROJECT_CORE1_PHASE_MODEL_END_CYCLE (PROJECT_CORE1_PHASE_MODEL_START_CYCLE + 3000u)
#define PROJECT_CORE1_PHASE_MODEL_WCET_CYCLES 3000u

#define PROJECT_CORE1_PHASE_SYNC_TRIGGER_START_CYCLE PROJECT_CORE1_PHASE_MODEL_END_CYCLE
#define PROJECT_CORE1_PHASE_SYNC_TRIGGER_WCET_CYCLES (21800u + PROJECT_CORE1_PRIORITY_RX_PHASE_CYCLES)
#define PROJECT_CORE1_PHASE_SYNC_TRIGGER_END_CYCLE \
    (PROJECT_CORE1_PHASE_SYNC_TRIGGER_START_CYCLE + PROJECT_CORE1_PHASE_SYNC_TRIGGER_WCET_CYCLES + \
     PROJECT_CORE1_PRIORITY_RX_CLOSE_CYCLES + 200u)

#define PROJECT_CORE1_PHASE_TRIGGER_MEASURE_START_CYCLE PROJECT_CORE1_PHASE_SYNC_TRIGGER_END_CYCLE
#define PROJECT_CORE1_PHASE_TRIGGER_MEASURE_END_CYCLE (PROJECT_CORE1_PHASE_TRIGGER_MEASURE_START_CYCLE + 2000u)
#define PROJECT_CORE1_PHASE_TRIGGER_MEASURE_WCET_CYCLES 2000u

#define PROJECT_CORE1_PHASE_GUARD_START_CYCLE PROJECT_CORE1_PHASE_TRIGGER_MEASURE_END_CYCLE
#define PROJECT_CORE1_PHASE_GUARD_END_CYCLE PROJECT_CORE1_CYCLE_CYCLES
#define PROJECT_CORE1_PHASE_GUARD_WCET_CYCLES 0u

#ifndef PROJECT_ENABLE_WATCHDOG_TEST
#define PROJECT_ENABLE_WATCHDOG_TEST 0
#endif

#ifndef PROJECT_ENABLE_HEALTH_LOG
#define PROJECT_ENABLE_HEALTH_LOG 0
#endif

#ifndef PROJECT_ENABLE_TDMA_RING_LOG
#define PROJECT_ENABLE_TDMA_RING_LOG 0
#endif

#ifndef PROJECT_ENABLE_LOG_UART_OUTPUT
#define PROJECT_ENABLE_LOG_UART_OUTPUT 1
#endif

#ifndef PROJECT_ENABLE_OTA_FAULT_INJECTION
#define PROJECT_ENABLE_OTA_FAULT_INJECTION 0
#endif

#ifndef PROJECT_ENABLE_FLASH_VALIDATION
#define PROJECT_ENABLE_FLASH_VALIDATION 0
#endif

#ifndef PROJECT_OTA_DEFAULT_BOOT_MODE_DIRECT_AB
#define PROJECT_OTA_DEFAULT_BOOT_MODE_DIRECT_AB 1
#endif

#define BOARD_SPI_BAUD_HZ 10000000u
#define BOARD_UART_BAUD_HZ 115200u

#ifndef PROJECT_ENABLE_USB_STDIO
#define PROJECT_ENABLE_USB_STDIO 1
#endif

#ifndef PROJECT_ENABLE_UART_STDIO
#define PROJECT_ENABLE_UART_STDIO 0
#endif

#ifndef PROJECT_ENABLE_USBTMC
#define PROJECT_ENABLE_USBTMC 0
#endif

#ifndef PROJECT_ENABLE_USB_RUNTIME_SWITCH
#define PROJECT_ENABLE_USB_RUNTIME_SWITCH 0
#endif

#ifndef PROJECT_USB_DEFAULT_MODE_USBTMC
#define PROJECT_USB_DEFAULT_MODE_USBTMC 0
#endif

#ifndef PROJECT_USB_VID
#define PROJECT_USB_VID 0xCAFEu
#endif

#ifndef PROJECT_USB_PID_CDC
#define PROJECT_USB_PID_CDC 0x402Fu
#endif

#ifndef PROJECT_USB_PID_USBTMC
#define PROJECT_USB_PID_USBTMC 0x4030u
#endif

#define PROJECT_USB_MANUFACTURER PROJECT_VENDOR_NAME
#define PROJECT_USB_PRODUCT "GTS DHRT100"
#define PROJECT_USB_PRODUCT_USBTMC PROJECT_USB_PRODUCT
#define PROJECT_USB_PRODUCT_CDC PROJECT_USB_PRODUCT

#endif
