#ifndef TDMA_STATE_MACHINE_RESOURCES_H
#define TDMA_STATE_MACHINE_RESOURCES_H

/* Static direction/resource contract for the cyclic flight persona.  The
 * values are board-owned in board_config.h; this header only validates their
 * relationships and provides one stable interface for DeploymentGate/tests. */
#include "board_config.h"

#if BOARD_TDMA_TX_PIO_BLOCK_ID == BOARD_TDMA_RX_PIO_BLOCK_ID
#error "TDMA TX and RX flight PIO blocks must be distinct"
#endif
#if BOARD_TDMA_TX_PIO_BLOCK_ID == BOARD_TDMA_SMA_PIO_BLOCK_ID || \
    BOARD_TDMA_RX_PIO_BLOCK_ID == BOARD_TDMA_SMA_PIO_BLOCK_ID
#error "TDMA flight PIO blocks must not overlap SMA PIO"
#endif
#if BOARD_TDMA_TX_CLK_OUT_SM == BOARD_TDMA_TX_SYNC_OUT_SM || \
    BOARD_TDMA_TX_CLK_OUT_SM == BOARD_TDMA_TX_DATA_IN_FORWARD_SM || \
    BOARD_TDMA_TX_CLK_OUT_SM == BOARD_TDMA_TX_DATA_IN_CAPTURE_SM || \
    BOARD_TDMA_TX_SYNC_OUT_SM == BOARD_TDMA_TX_DATA_IN_FORWARD_SM || \
    BOARD_TDMA_TX_SYNC_OUT_SM == BOARD_TDMA_TX_DATA_IN_CAPTURE_SM || \
    BOARD_TDMA_TX_DATA_IN_FORWARD_SM == BOARD_TDMA_TX_DATA_IN_CAPTURE_SM
#error "TDMA TX logical-port SM roles must be unique"
#endif
#if BOARD_TDMA_RX_CLK_IN_SM == BOARD_TDMA_RX_SYNC_IN_SM || \
    BOARD_TDMA_RX_CLK_IN_SM == BOARD_TDMA_RX_DATA_OUT_SM || \
    BOARD_TDMA_RX_CLK_IN_SM == BOARD_TDMA_RX_EVIDENCE_IN_SM || \
    BOARD_TDMA_RX_SYNC_IN_SM == BOARD_TDMA_RX_DATA_OUT_SM || \
    BOARD_TDMA_RX_SYNC_IN_SM == BOARD_TDMA_RX_EVIDENCE_IN_SM || \
    BOARD_TDMA_RX_DATA_OUT_SM == BOARD_TDMA_RX_EVIDENCE_IN_SM
#error "TDMA RX logical-port SM roles must be unique"
#endif
#if BOARD_TDMA_TX_DATA_IN_CAPTURE_DMA_CHANNEL == BOARD_TDMA_RX_DATA_OUT_DMA_CHANNEL || \
    BOARD_TDMA_TX_DATA_IN_CAPTURE_DMA_CHANNEL == BOARD_TDMA_TX_DATA_IN_FORWARD_DMA_CHANNEL || \
    BOARD_TDMA_TX_DATA_IN_CAPTURE_DMA_CHANNEL == BOARD_TDMA_TX_SYNC_EDGE_DMA_CHANNEL || \
    BOARD_TDMA_RX_DATA_OUT_DMA_CHANNEL == BOARD_TDMA_TX_DATA_IN_FORWARD_DMA_CHANNEL || \
    BOARD_TDMA_RX_DATA_OUT_DMA_CHANNEL == BOARD_TDMA_TX_SYNC_EDGE_DMA_CHANNEL || \
    BOARD_TDMA_TX_DATA_IN_FORWARD_DMA_CHANNEL == BOARD_TDMA_TX_SYNC_EDGE_DMA_CHANNEL
#error "TDMA logical-port DMA channels must be unique"
#endif

#define TDMA_STATE_MACHINE_RESOURCE_CONTRACT_VERSION 1u
#define TDMA_STATE_MACHINE_RESOURCE_CONTRACT_DIRECTIONAL 1u

#endif
